version: '3'

services:
  # Spring Boot Application
  spring-boot-app:
    image: backend
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/demo
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATA_SOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    depends_on:
      - mysql
    networks:
      - backend

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'demo'
      MYSQL_ROOT_USERNAME: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - backend
    ports:
      - '3306:3306'
    volumes:
      - demo:/var/lib/mysql

  # Angular application
  angular-app:
    image: frontend
    ports:
      - "4200:80"
    depends_on:
      - spring-boot-app
    networks:
      - frontend

networks:
  backend:
    driver: bridge

  frontend:
    driver: bridge

volumes:
  demo:
    driver: local

